openapi: "3.0.2"
info:
  title: Cache API
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /cache/{key}:
    parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        200:
          content:
            text/plain:
              schema:
                type: string
          description: Returns a cache value for key
        404:
          description: Can't find cache entry for key
    put:
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        description: Value to be set in cache under key
      responses:
        204:
          description: Cache entry updated/created
    delete:
      description: Removes value from key, ignores if not exists
      responses:
        204:
          description: Cache entry removed
        404:
          description: Cache entry to delete not found